<a href="https://colab.research.google.com/github/Nitesh-kelwani/DL-with-Pythorch/blob/main/NN_bonus_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

# Load data from CSV file
df = pd.read_csv("bonus.csv")
df.head()

,employee_id,performance,years_of_experience,projects_completed,bonus
0,EMP_001,7,1,3,116
1,EMP_002,4,8,10,136
2,EMP_003,8,4,5,150
3,EMP_004,5,4,7,118
4,EMP_005,7,5,6,146


In [ ]:
df.shape

(1000, 5)

In [ ]:
from sklearn.model_selection import train_test_split

# Separate features and target
X = df[['performance', 'years_of_experience', 'projects_completed']].values
y = df[['bonus']].values  # Ensure target is a 2D array for compatibility

# Split data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim

# Seed for reproducibility
torch.manual_seed(0)

# Convert to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
Y_train_tensor = torch.tensor(y_train, dtype=torch.float32)
Y_test_tensor = torch.tensor(y_test, dtype=torch.float32)

In [ ]:
class Bonuspredictor(nn.Module):
  def __init__(self):
    super().__init__()
    self.network= nn.Sequential(
        nn.Linear(3,1)
    )
  def forward(self,x):
    return self.network(x)

In [ ]:
model=Bonuspredictor()
criterion=nn.MSELoss()
optimizer=torch.optim.SGD(model.parameters(),lr=0.005)

In [ ]:
epochs=5000

for epoch in range(epochs):
  #1. Forwrd Pass
  predictions=model(X_train_tensor)
  loss=criterion(predictions,Y_train_tensor)
  #2. Backward pass
  optimizer.zero_grad()
  loss.backward()
  #3.updated weightd
  optimizer.step()

  # Print loss every 100 epochs
  if (epoch + 1) % 100 == 0:
      print(f"Epoch [{epoch + 1}/{epochs}], Loss: {loss.item():.2f}")

Epoch [100/5000], Loss: 20.49
Epoch [200/5000], Loss: 17.97
Epoch [300/5000], Loss: 15.80
Epoch [400/5000], Loss: 13.90
Epoch [500/5000], Loss: 12.24
Epoch [600/5000], Loss: 10.77
Epoch [700/5000], Loss: 9.48
Epoch [800/5000], Loss: 8.35
Epoch [900/5000], Loss: 7.35
Epoch [1000/5000], Loss: 6.47
Epoch [1100/5000], Loss: 5.70
Epoch [1200/5000], Loss: 5.02
Epoch [1300/5000], Loss: 4.42
Epoch [1400/5000], Loss: 3.89
Epoch [1500/5000], Loss: 3.43
Epoch [1600/5000], Loss: 3.02
Epoch [1700/5000], Loss: 2.66
Epoch [1800/5000], Loss: 2.34
Epoch [1900/5000], Loss: 2.06
Epoch [2000/5000], Loss: 1.81
Epoch [2100/5000], Loss: 1.60
Epoch [2200/5000], Loss: 1.40
Epoch [2300/5000], Loss: 1.24
Epoch [2400/5000], Loss: 1.09
Epoch [2500/5000], Loss: 0.96
Epoch [2600/5000], Loss: 0.84
Epoch [2700/5000], Loss: 0.74
Epoch [2800/5000], Loss: 0.65
Epoch [2900/5000], Loss: 0.58
Epoch [3000/5000], Loss: 0.51
Epoch [3100/5000], Loss: 0.45
Epoch [3200/5000], Loss: 0.39
Epoch [3300/5000], Loss: 0.35
Epoch [3400/5

In [ ]:
model.eval()

with torch.no_grad():
  test_predictions=model(X_test_tensor)
  test_loss=criterion(test_predictions,Y_test_tensor)

print(f"test Loss : {test_loss.item():0.2f}")

test Loss : 0.04


In [ ]:
X_test_tensor[:3]

tensor([[ 8.,  9., 10.],
        [ 9.,  2.,  5.],
        [ 3.,  7.,  8.]])

In [ ]:
test_predictions[:3]

tensor([[189.9588],
        [150.1526],
        [113.7363]])

In [ ]:
Y_test_tensor[:3]

tensor([[190.],
        [150.],
        [114.]])

In [ ]:
for name,value in model.named_parameters():
  print(f" Name: {name}, Value: {value}")

 Name: network.0.weight, Value: Parameter containing:
tensor([[12.0327,  5.8458,  2.1837]], requires_grad=True)
 Name: network.0.bias, Value: Parameter containing:
tensor([19.2481], requires_grad=True)
