<a href="https://colab.research.google.com/github/Nitesh-kelwani/DL-with-Pythorch/blob/main/pytorch_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
print(torch.__version__)
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

2.9.0+cu126
True
Tesla T4


In [ ]:
#0D tensor
a = torch.tensor(5)
print("0D Tensor:", a)

0D Tensor: tensor(5)


In [ ]:
revanue=torch.tensor([100,220,90,75])
revanue

tensor([100, 220,  90,  75])

In [ ]:
revanue[:3]

tensor([100, 220,  90])

In [ ]:
# Sales data for Quarter 1 (Matrix 1)
# Rows represent different products, columns represent different regions

q1 = torch.tensor([
    [200, 220, 250],  # Product A (iPhone)
    [150, 180, 210],  # Product B (iPad)
    [300, 330, 360]   # Product C (MacBook)
])

q2 = torch.tensor([
    [209, 231, 259],  # Product A (iPhone)
    [155, 192, 222],  # Product B (iPad)
    [310, 340, 375]   # Product C (MacBook)
])

In [ ]:
q1+q2

tensor([[409, 451, 509],
        [305, 372, 432],
        [610, 670, 735]])

In [ ]:
q2-q1

tensor([[ 9, 11,  9],
        [ 5, 12, 12],
        [10, 10, 15]])

In [ ]:
(q2-q1)*100/q1

tensor([[4.5000, 5.0000, 3.6000],
        [3.3333, 6.6667, 5.7143],
        [3.3333, 3.0303, 4.1667]])

In [ ]:
return_rate=0.1
return_rate*q1

tensor([[20., 22., 25.],
        [15., 18., 21.],
        [30., 33., 36.]])

In [ ]:
# profit per unit is given product and region wise
# calculate total profit for all units per region, per product
profit_per_unit = torch.tensor([
    [30,27,25],
    [20,18,17],
    [45,38,39]
])
# for this we can use *element wise multiplication*
q1 * profit_per_unit

tensor([[ 6000,  5940,  6250],
        [ 3000,  3240,  3570],
        [13500, 12540, 14040]])

In [ ]:
product_prices = torch.tensor([[1100, 450, 1500]])
product_prices

tensor([[1100,  450, 1500]])

In [ ]:
revenue_per_region_matrix = torch.matmul(product_prices, q1)
revenue_per_region_matrix

In [ ]:
q1

tensor([[200, 220, 250],
        [150, 180, 210],
        [300, 330, 360]])

In [ ]:
product_prices.t()

tensor([[1100],
        [ 450],
        [1500]])

In [ ]:
prices_by_region = q1*product_prices.t()
prices_by_region

tensor([[220000, 242000, 275000],
        [ 67500,  81000,  94500],
        [450000, 495000, 540000]])

In [ ]:
# Create portfolio composition matrix (3x3)
# Rows: Different portfolios (P1, P2, P3)
# Columns: Asset allocation (Stocks, Bonds, Real Estate)
portfolio_composition = torch.tensor([
    [100.0, 50.0, 30.0],  # P1
    [80.0, 70.0, 20.0],   # P2
    [60.0, 40.0, 90.0]    # P3
], dtype=torch.float32)

# Create price change matrix (3x3)
# Rows: Assets (Stocks, Bonds, Real Estate)
# Columns: Economic scenarios (Growth, Neutral, Recession)
price_changes = torch.tensor([
    [1.15, 1.05, 0.85],  # Stocks
    [1.05, 1.02, 1.10],  # Bonds
    [1.10, 1.00, 0.90]   # Real Estate
], dtype=torch.float32)

values = torch.matmul(portfolio_composition, price_changes)
values

tensor([[200.5000, 186.0000, 167.0000],
        [187.5000, 175.4000, 163.0000],
        [210.0000, 193.8000, 176.0000]])

In [ ]:
# Assume that this portfolio is in USD. You want to convert that to INR
# Assume USD to INR conversion rate to be 83

values_inr = 83*values
values_inr

tensor([[16641.5000, 15438.0000, 13861.0000],
        [15562.5000, 14558.1992, 13529.0000],
        [17430.0000, 16085.3994, 14608.0000]])

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("Using GPU for large-scale customer data processing")
else:
    device = torch.device("cpu")
    print("Using CPU for customer data processing")

Using GPU for large-scale customer data processing


In [ ]:
# Simulating customer data with 1 million customers and 3 features (age, spending score, income)
customer_data = torch.rand(1_000_000, 3, device=device)
customer_data.shape

torch.Size([1000000, 3])

In [ ]:
customer_data[:5]

tensor([[0.5925, 0.5771, 0.0926],
        [0.0651, 0.1620, 0.8165],
        [0.2070, 0.9566, 0.0567],
        [0.6293, 0.1299, 0.8848],
        [0.5747, 0.3922, 0.2177]], device='cuda:0')

In [ ]:
high_spending_customers = customer_data[customer_data[:, 1] > 0.5]
high_spending_customers

tensor([[0.5925, 0.5771, 0.0926],
        [0.2070, 0.9566, 0.0567],
        [0.0384, 0.9589, 0.2930],
        ...,
        [0.9514, 0.9488, 0.3827],
        [0.4238, 0.7740, 0.3421],
        [0.4615, 0.7165, 0.0319]], device='cuda:0')

In [ ]:
high_spending_customers.shape

torch.Size([499413, 3])

In [ ]:
high_spending_customers_cpu = high_spending_customers.to("cpu")