<a href="https://colab.research.google.com/github/Nitesh-kelwani/DL-with-Pythorch/blob/main/tensor_basics_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

### Tensor Attributes

In [ ]:
units = torch.tensor([
    [200, 220],  # Product A (iPhone)
    [150, 180],  # Product B (iPad)
    [300, 330]   # Product C (MacBook)
])

In [ ]:
units.shape

torch.Size([3, 2])

In [ ]:
units.dtype

torch.int64

In [ ]:
units.device

device(type='cpu')

### Tensor Reshaping

In [ ]:
units.view(-1)

tensor([200, 220, 150, 180, 300, 330])

In [ ]:
units.view(2,3)

tensor([[200, 220, 150],
        [180, 300, 330]])

In [ ]:
units.view(6,1)

tensor([[200],
        [220],
        [150],
        [180],
        [300],
        [330]])

### Index Operator

In [ ]:
units

tensor([[200, 220],
        [150, 180],
        [300, 330]])

In [ ]:
units[2,0]

tensor(300)

In [ ]:
units[2,0] = 305
units

tensor([[200, 220],
        [150, 180],
        [305, 330]])

### Tensor Creation with Specific Values

In [ ]:
torch.zeros((2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
torch.ones((3,5))

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [ ]:
torch.rand((3,5))

tensor([[0.0362, 0.3159, 0.0490, 0.3862, 0.8634],
        [0.9358, 0.6817, 0.2900, 0.9191, 0.6607],
        [0.2398, 0.7497, 0.7850, 0.9150, 0.6991]])